# Generated by Django 3.1.4 on 2021-06-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20200211_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=255, verbose_name='教室類型'),
        ),
        migrations.AlterField(
            model_name='book',
            name='preface',
            field=models.ImageField(upload_to='', verbose_name='教室圖片'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255, verbose_name='教室號碼'),
        ),
    ]
